"""initial_migration

Revision ID: 8db955ab6b02
Revises: 
Create Date: 2026-05-24 14:39:45.626719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db955ab6b02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Nos aseguramos de que las columnas existan antes de hacer nada más
    op.execute("ALTER TABLE chat ADD COLUMN IF NOT EXISTS app_id VARCHAR(50) DEFAULT 'jarvis-default';")
    op.execute("ALTER TABLE user_identities ADD COLUMN IF NOT EXISTS app_id VARCHAR(50) DEFAULT 'jarvis-default';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_chat_user_app_context;")
    op.create_index(op.f('ix_chat_app_id'), 'chat', ['app_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS documents_embedding_idx;")
    op.alter_column('user_identities', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', 'CLERK', 'AWS', 'MANUAL', name='authprovider'),
               existing_nullable=False,
               postgresql_using="provider::text::authprovider")
    op.execute("DROP INDEX IF EXISTS idx_identities_lookup;") 
    op.drop_constraint(op.f('user_identities_app_id_provider_provider_user_id_key'), 'user_identities', type_='unique')
    op.create_unique_constraint('_provider_user_uc', 'user_identities', ['provider', 'provider_user_id'])
    op.create_index(op.f('ix_user_identities_app_id'), 'user_identities', ['app_id'], unique=False)
    op.drop_constraint(op.f('user_identities_user_id_fkey'), 'user_identities', type_='foreignkey')
    op.create_foreign_key(None, 'user_identities', 'users', ['user_id'], ['id'])
    op.drop_column('user_identities', 'created_at')
    op.alter_column('user_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('user_identities', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_identities', type_='foreignkey')
    op.create_foreign_key(op.f('user_identities_user_id_fkey'), 'user_identities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_identities_app_id'), table_name='user_identities')
    op.drop_constraint('_provider_user_uc', 'user_identities', type_='unique')
    op.create_unique_constraint(op.f('user_identities_app_id_provider_provider_user_id_key'), 'user_identities', ['app_id', 'provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_identities_lookup'), 'user_identities', ['app_id', 'provider', 'provider_user_id'], unique=False)
    op.alter_column('user_identities', 'provider',
               existing_type=sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', 'CLERK', 'AWS', 'MANUAL', name='authprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_chat_app_id'), table_name='chat')
    op.create_index(op.f('idx_chat_user_app_context'), 'chat', ['user_id', 'app_id'], unique=False)
    # ### end Alembic commands ###
