"""Add HITL Models

Revision ID: afbc4e2d72c7
Revises: 8db955ab6b02
Create Date: 2026-05-31 15:09:37.856572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afbc4e2d72c7'
down_revision: Union[str, Sequence[str], None] = '8db955ab6b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'WAITING', 'COMPLETED', 'TIMEOUT', 'FAILED', name='agentstatus'), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('steps_total', sa.Integer(), nullable=True),
    sa.Column('checkpoint_data', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_created_at'), 'agent_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('hitl_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('matched_rule', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.Enum('SAFE', 'WARN', 'BLOCK', name='hitlrisklevel'), nullable=False),
    sa.Column('verdict', sa.Enum('BLOCKED', 'PENDING', 'APPROVED', 'REJECTED', name='hitlverdict'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_logs_chat_id'), 'hitl_logs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_hitl_logs_created_at'), 'hitl_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_hitl_logs_session_id'), 'hitl_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_hitl_logs_user_id'), 'hitl_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_hitl_logs_verdict'), 'hitl_logs', ['verdict'], unique=False)
    #op.add_column('chat', sa.Column('app_id', sa.String(length=50), server_default='jarvis-default', nullable=False))
    #op.create_index(op.f('ix_chat_app_id'), 'chat', ['app_id'], unique=False)
    #op.drop_index(op.f('documents_embedding_idx'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('user_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    #op.drop_constraint(op.f('users_clerk_id_key'), 'users', type_='unique')
    #op.drop_column('users', 'clerk_id')
    #op.drop_column('users', 'password_hash')
    #op.drop_column('users', 'auth_provider')
    #op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auth_provider', postgresql.ENUM('LOCAL', 'GOOGLE', 'GITHUB', 'CLERK', name='authprovider'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_clerk_id_key'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_token', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    #op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_chat_app_id'), table_name='chat')
    op.drop_column('chat', 'app_id')
    op.drop_index(op.f('ix_hitl_logs_verdict'), table_name='hitl_logs')
    op.drop_index(op.f('ix_hitl_logs_user_id'), table_name='hitl_logs')
    op.drop_index(op.f('ix_hitl_logs_session_id'), table_name='hitl_logs')
    op.drop_index(op.f('ix_hitl_logs_created_at'), table_name='hitl_logs')
    op.drop_index(op.f('ix_hitl_logs_chat_id'), table_name='hitl_logs')
    op.drop_table('hitl_logs')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_created_at'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
