"""Add auth_provider and Google fields to User

Revision ID: ba4913e606cf
Revises: 329f82442478
Create Date: 2025-07-04 22:12:34.722448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4913e606cf'
down_revision: Union[str, Sequence[str], None] = '329f82442478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.Enum('local', 'google', 'github', name='authprovider'), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('locale', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locale')
        batch_op.drop_column('picture')
        batch_op.drop_column('google_id')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
