name: Deploy Build to Azure Functions

on:
  push:
    branches: [ "master" ]  # Dispara el despliegue al hacer push a master/main

env:
  AZURE_FUNCTIONAPP_NAME: mcp-build-gustavo  # Nombre de tu Function App en Azure
  PYTHON_VERSION: '3.12'                     # Versión de Python

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Opcional: Define un entorno (útil para approvals)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener este archivo
        working-directory: backend

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
         
      - name: Set enireoment variables in Azure
        uses: Azure/cli@v1
        with:
            inlineScript: |
                az functionapp config appsettings set \
                --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
                --resource-group ${{ env.RESOURCE_GROUP }} \
                --settings \
                    OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                    DEEP_API_KEY="${{ secrets.DEEP_API_KEY }}" \
                    QWEN3_KEY="${{ secrets.QWEN3_KEY }}" \
                    GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}""
