name: Build and Deploy to Azure Functions
on:
  push:
    branches: [ "master" ]
    

env:
  AZURE_FUNCTIONAPP_NAME: mcp-build-gustavo
  RESOURCE_GROUP: "DefaultResourceGroup-EUS"  # <-- ¡Reemplaza esto!
  PYTHON_VERSION: "3.12"

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: backend/functions

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}

      - name: Set environment variables in Azure
        uses: azure/cli@v2  # ¡Nota: "azure/cli" en minúscula!
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --settings \
                OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                DEEP_API_KEY="${{ secrets.DEEP_API_KEY }}" \
                QWEN3_KEY="${{ secrets.QWEN3_KEY }}" \
                GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"  # Sin comilla extra al final